### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by lrharris215** [lrharris215/coal#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] Guest Sign-in

**Comment by danemauland** [comment]
Hi Lane,

Overall your site looks good and whole functionality for user auth seems to be working flawlessly. There are quite a few areas, though, where your site isn't pixel-perfect:

# Splash
## Navbar
height is off
Elements are not centered horizontally
Your font for everything except the logo seems too large
Missing color change on hover for everything except the logo
Missing cursor change to pointer when hovering over language chevron
Where does "about" come from in the store dropdown? I'm not seeing that on steam

## Sidebar
Missing color change on hover for the links

# Sign In
Font weight on the h1 seems too heavy
The background image positioning is off
The sign in form/component with the sign up link look like they're centered in their background areas--on Steam, they appear closer together
The height on your inputs looks off
Your inputs are spaced too far apart
If you click in the inputs, the cursor is all the way to the left. Steam has a bit of padding here.
Steam's inputs have rounded edges
Extend the background color all the way to the bottom of the page
Background for the "Join Coal" section looks too dark
The hover events for "Learn More" can be triggered very far to the right (funnily enough, steam also has a somewhat absurd range for the hover on their "forgot your password" link
Spacing between the computer image and the text right below it seems too tight
Error message font seems too small and the font should be aligned to the left, not centered
The Sign In button has a white border when clicking on it
Their error message box has a transition on it when it appears
You're missing a . on the end of the error message
When the sign up or log in form component mounts, you should dispatch a "CLEAR_ERRORS" action or something similar so error messages don't carry over from the sign in page to sign up or vice-versa

# Sign Up
A lot of the above applies here
Your form is too far to the left
They title the page "create your account", not "sign up"
Your title should be left aligned
Nice touch with the CAPTCHA. I'm not going to be too picky with it, just make sure it's aligned with the inputs above it
The age checkbox should be indented a little and the checkbox should be a bit bigger
Sign Up button should be aligned with the start of the inputs
The div with the opacity looks off--I can see a straight line where it ends (it goes through the fallout guy's thumb, at least on my screen)
Multiple error messages get smashed together
It allows me to sign in without checking the 13 years old or older checkbox
Inputs with errors receive a red border

**Comment by lrharris215** [comment]
Ok made all the changes! The Guest button now fills in the fields with guest info before submitting, which I think is fine?

**Comment by danemauland** [comment]
Great work! One more round of edits and I think you'll be good!

# Splash Width of your sidebar li's is 230px, steam's is 210px
Font weight on install steam/login/language seems too heavy
Hover effect on install coal button missing
More space needed between login and language (this will also help mask the vertical alignment issue caused by the language chevron)

# Sign In
I'm not seeing the border effect on mouse-down on the sign-in button on steam--If you want to add it in that's fine, but it currently pushes other elements down. To avoid this, set a border on the button that is the same width as the border you want to appear when you click. On mousedown, change the color of this border to white.
Slow down the transition for when the error box appears

# Sign Up
Make error borders around the inputs 1px

**Comment by lrharris215** [comment]
Hey so I made all the changes. The error box transition is set to 2 seconds now, with a half second delay. Looks a lot smoother.

**Comment by danemauland** [comment]
Instead of setting the li width to 210, set in on the sidebar itself so it doesn't take up the whole page (and the li's will fill it automatically)

Nothing to change here but I just noticed Steam's border on button click happens in Chrome but not in Firefox, which is why I said in the notes above that I wasn't seeing the border effect. Weird.

Errors
Consider changing the color of the red for error messages to match the maroon background color, I think this might be better aesthetically

**Comment by lrharris215** [comment]
Ok I fixed the side bar. Making the error message border maroon looked really bad though, you could barely see it. I tried changing it to the reds from the gradient but I think they were still too muted. I did make the error red a little bit darker though.

**Comment by danemauland** [comment]
Okay great! At some point you're going to want to add in a loading icon for while the server is processing the login/sign up but I consider your first MVP to be done now, congrats!

**Comment by lrharris215** [comment]
Ok great!!! Thanks Dane!
