### ISSUE TITLE
PA Review: Games Listings

### ISSUE THREAD

**Issue by lrharris215** [lrharris215/coal#9]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by lrharris215** [comment]
So a few notes: Scrollbar is missing on the show page because I didn't add that many pictures and I will have to build it from scratch to make it look nice. I didn't think it was crucial to the listings MVP. 

Same with the tabs on the index portion. I have no way to measure top sellers, or popular games yet. I could add fake tabs though? 

There is a sharp divider on the index background because on steam there are more things between the feature carousel and the index. Wasn't sure what to do about that, so it's right underneath for now.

**Comment by danemauland** [comment]
# Your comments
1. that's fine
2. fine as is. Going forward, avoid adding anything to the page unless you're going to be adding functionality (so no more fake tabs, links, etc)
3. that's fine. Maybe just have this section have a transparent background so that sharp divider isn't there. I'll leave this one up to you.

# Landing Page
Let's revisit the structure now that we have some content here. It looks like Steam centers the main content. The items in the header are also constrained to this area. Then, the sidebar is just to the left of the main content, instead of all the way to the left of the page. Try to replicate that layout. Let me know if anything is unclear.
The carousel and the content below it should be centered in relation to each other.

# Game Show Page
Right now, clicking one of the images to change the displayed image adds a border around the selected image. This border pushes the images to the right of it a couple pixels. The easiest way to see this is to click the first image and then click the last, you will see the images shifting a little bit. One way to avoid this is to a transparent border around all the images, and change the color when it's selected
The Buy section doesn't seem to be centered properly

**Comment by lrharris215** [comment]
Fixed the layouts on the home and show page. Deleted the background on the index, definitely looks better without it. Adjusted the header a little bit, should be lined up better now.

**Comment by lrharris215** [comment]
Ok I think I fixed the layout issues. Added a media query so it wouldn't look weird on my laptop, but everything should be centered on larger screens now. Also added a media query for the login/signup forms so that should look better too.
